### ISSUE TITLE
Adding new regexp

### ISSUE THREAD

**Issue by xdgimf** [openbibleinfo/Bible-Passage-Reference-Parser#26]
Where to add new regexp or pattern?
Is it okay to add it in regexps.coffee?

**Comment by openbibleinfo** [comment]
If you're looking to create a local fork, you could add it directly to regexps.coffee or the compiled bcv_parser for the relevant language. Otherwise, you can add the abbreviation to the "data.txt" file for the language and then recompile all the patterns. See https://github.com/openbibleinfo/Bible-Passage-Reference-Parser#build-instructions (especially steps 3-5).

I've been considering whether to make it easier to add custom patterns at runtime, but for now, editing the source or rebuilding the complete language files are your options.

**Comment by xdgimf** [comment]
Oh thanks, anyway whats the use of research.xlsx?

**Comment by openbibleinfo** [comment]
Those files let you know the source of the book names and abbreviations if you ever want to reconstruct where they came from.
