### ISSUE TITLE
OSIS .toString

### ISSUE THREAD

**Issue by jamlen** [openbibleinfo/Bible-Passage-Reference-Parser#7]
Is there a method available on the OSIS to give it back in a human readable format?

For example: `'1Cor.2.5' => '1 Corinthians 2:5'`

**Comment by a-am** [comment]
This script has been very helpful. Thank you.  However when testing ```1Cor.1.3-1Cor.1.10``` it returns ```1 Corinthians 3-10```.

**Comment by a-am** [comment]
I believe I have found the issue.  In the method **is_single_chapter_book** 
 ```[start, end] = osis.split "-"``` should be changed to ```[start, end] = osis.split "."```

**Comment by openbibleinfo** [comment]
When I take the code above and run `osis_to_readable("long", "1Cor.1.3-1Cor.1.10")`, it returns `1 Corinthians 1:3-10` for me. Your second comment suggests that maybe you're not using `osis_compaction_strategy: "bcv"`?

The `is_single_chapter_book` function basically checks whether, say, "1Cor 2" is a chapter (and thus has more than one chapter) or a verse, assuming that the "bcv" `osis_compaction_strategy` will return a range if it's a chapter. You could achieve the same result by `split`ting on the `.` and seeing whether the second element returned is equal to `1` (single-chapter book) or `2` (multi-chapter book). Then the function wouldn't rely on a specific `osis_compaction_strategy`.

**Comment by a-am** [comment]
How would I not be using the *osis_compaction_strategy: "bcv"* if I am passing in a valid osis reference? I am using the same method with parameters  ```osis_to_readable("long", "1Cor.1.3-1Cor.1.10")``` when testing the reference. Thank you for your time & code!

**Comment by openbibleinfo** [comment]
Here's the relevant line in the above code:

`bcv.set_options osis_compaction_strategy: "bcv", book_alone_strategy: "full", book_sequence_strategy: "include", consecutive_combination_strategy: "combine", book_range_strategy: "include"`

The `osis_compaction_strategy` controls the output from the `bcv_parser`, not its input; it affects how specific you want the output to be. So, given the input "Gen 1-50", a `b` strategy returns "Gen"; a "bc" strategy returns "Gen.1-Gen.50", and a "bcv" strategy returns "Gen.1.1-Gen.50.26". All are correct but are at varying levels of detail.

The above code uses "bcv" because "bcv" always returns a range if more than one verse is involved, which is convenient for several of the functions. The default is "b", which assumes you want the shortest available osis that can represent the input.

The above code also assumes that the other options are set as above; the output of `osis_to_readable` might be unexpected if they're set differently. Hope that helps!

**Comment by openbibleinfo** [comment]
For future readers of this topic, I've since created a repo that converts from OSIS to a human-readable format: https://github.com/openbibleinfo/Bible-Reference-Formatter
